---
openapi: "3.0.2"
info:
  title: "Rest API FSTR"
  version: '1.0'
  description: "Реализованы методы для добавления, просмотра и изменения пройденных перевалов"
tags:
  - name: "objects"
paths:
  /submitData:
    post:
      tags:
      - "objects"
      operationId: "create_pereval"
      description: "Добавить данные о прохождении нового перевала"
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pereval'
          required: true
      responses:
        '200':
          description: "Объект создан"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreationResponse'
        '400':
          description: "Ошибка при заполнении"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreationResponse'
        '500':
          description: "Ошибка при обработке на сервере"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreationResponse'
  /submitData/:
    get:
      tags:
      - "objects"
      operationId: "filter_list_Pereval"
      description: "Получение списка всех перевалов пользователя с данным email"
      parameters:
        - name: "user_email"
          in: "query"
          required: true
          description: "email пользователя"
          schema:
            type: "string"
      responses:
        '200':
          description: "Ответ получен"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Pereval'
        '500':
          description: "Ошибка при обработке на сервере"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortResponse'
  /submitData/{id}:
    get:
      tags:
      - "objects"
      operationId: "retrieve_Pereval"
      description: "Получить информацию по id объекта"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "Уникальный идентификатор перевала"
          schema:
            type: "string"
      responses:
        '200':
          description: "Объект получен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pereval'
        '404':
          description: "Такого объекта не существует"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortResponse'
        '500':
          description: "Ошибка при обработке на сервере"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortResponse'
    patch:
      tags:
      - "objects"
      operationId: "partial_update_Pereval"
      description: "Изменить данные выбранного по id объекта"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "Уникальный идентификатор отчета"
          schema:
            type: "string"
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pereval'
          required: true
      responses:
        '200':
          description: "Объект изменен"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchSuccessResponse'
        '400':
          description: "Изменение невозможно"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchFailResponse'
        '404':
          description: "Объект не найден"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchFailResponse'
        '500':
          description: "Ошибка при обработке на сервере"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PatchFailResponse'
components:
  schemas:
    CreationResponse:
      type: "object"
      properties:
        message:
          type: "string"
          description: "создан новый объект"
        id:
          type: "integer"
          nullable: true
          description: "Идентификатор созданного объекта или null"
        status:
          type: "integer"
          description: "Код HTTP, полученный в результате обработки"
    ShortResponse:
      type: "object"
      properties:
        status:
          type: "integer"
          description: "Код HTTP, полученный в результате обработки"
        message:
          type: "string"
          description: "Строка описания статуса"
    PatchSuccessResponse:
      type: "object"
      properties:
        status:
          type: "integer"
          description: "Код HTTP, полученный в результате обработки"
        state:
          type: "integer"
          const: 1
          description: "Код состояния (1)"
        message:
          type: "string"
          description: 'Запись обновлена'
    PatchFailResponse:
      type: "object"
      properties:
        status:
          type: "integer"
          description: "Код HTTP, полученный в результате обработки"
        state:
          type: "integer"
          const: 0
          description: "Код состояния (0)"
        message:
          type: "string"
          description: "Строка описания статуса"
    Pereval:
      type: "object"
      properties:
        id:
          type: "integer"
          description: "Уникальный идентификатор перевала в базе данных"
          readOnly: true
        status:
          type: "string"
          description: "Статус обработки перевала"
          enum:
            - "new"
            - "pending"
            - "accepted"
            - "rejected"
          readOnly: true
        beauty_title:
          type: "string"
          maxLength: 30
          description: "Название горного объекта"
        title:
          type: "string"
          maxLength: 255
          description: "Наименование перевала"
        other_titles:
          type: string
          maxLength: 255
          description: "Другие известные наименования перевала"
        connects:
          type: "string"
          maxLength: 255
          description: "Что соединяет перевал"
        weather:
          type: "string"
          description: "время года, в которое выполнен маршрут"
          enum:
            - "winter"
            - "spring"
            - "summer"
            - "autumn"
        level:
          type: "string"
          description: "уровень сложности маршрута"
          enum:
            - "1А"
            - "1Б"
            - "2А"
            - "2Б"
            - "3А"
            - "3Б"
        add_time:
          type: "string"
          format: "date-time"
          description: "Дата и время добавления"
        coords:
          type: "object"
          properties:
            latitude:
              type: "number"
              format: "float"
              description: "Географическая широта объекта"
            longitude:
              type: "number"
              format: "float"
              description: "Географическая долгота объекта"
            height:
              type: "integer"
              description: "Высота объекта"
          required:
            - "latitude"
            - "longitude"
            - "height"
        user:
          type: "object"
          properties:
            name:
              type: "string"
              maxLength: 255
              description: "Имя пользователя"
            surname:
              type: "string"
              maxLength: 255
              description: "Фамилия пользователя"
            patronymic:
              type: "string"
              maxLength: 255
              description: "Отчество пользователя"
            email:
              type: "string"
              format: "email"
              maxLength: 255
              description: "Адрес e-mail пользователя"
            phone:
              type: "string"
              maxLength: 20
              description: "Телефон пользователя"
          required:
            - "email"
        images:
          type: "array"
          description: "Вложенные изображения"
          items:
            type: "object"
            properties:
              title:
                type: "string"
                maxLength: 255
                description: "Название изображения"
              date_added:
                type: "string"
                format: "date-time"
                description: "Дата добавления изображения"
              img:
                type: "string"
                format: "url"
                description: "ссылка на загруженное изображение"
      required:
      - "beauty_title"
      - "title"
      - "add_time"
      - "coords"
      - "user"
